### ISSUE TITLE
Example did not work as expected: HTML was escaped

### ISSUE THREAD

**Issue by stevedonovan** [stevelacy/daz#2]
Which was easy to fix, line 58 of daz.go calls `escape()` on the result of *calling the function*.

**Comment by stevedonovan** [comment]
Ah, I see the issue - there is `type HTML func() string` but it is not an alias - it is a new type....unless I'm misunderstanding the intent here.

**Comment by stevelacy** [comment]
Thanks for pointing that out, I had not updated the examples with the latest changes on daz.go
https://github.com/stevelacy/daz/commit/eaee30827cb125c100c6cc41aaeee67b6d416895
Cheers!
